import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Pack Viral",
   // TODO: Adicionar metadados do aplicativo para melhoria do SEO
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html className="bg-background" lang="pt-BR">
         <body className={`${geistSans.variable} antialiased font-sans text-white`}>{children}</body>
      </html>
   );
}
